### ISSUE TITLE
nested zoom filter selectors assign rules to wrong layer

### ISSUE THREAD

**Issue by sk1p** [mapbox/carto#107]
The following stylesheet:

``` css
#coastline {
  line-width: .5;
  line-color: #000;
  polygon-fill: #fff;
}
```

``` css
#bar [zoom>2] {
  [zoom>2] {
    [ScaleRank=6] {
      polygon-fill: #f00;
      polygon-opacity: .3;
    }
  }
}
```

generates the following Styles:

``` xml
<Style name="bar" filter-mode="first">
  <Rule>
    <Filter>([ScaleRank] = 6)</Filter>
    <PolygonSymbolizer fill="#ff0000" fill-opacity="0.3" />
  </Rule>
</Style>
```

``` xml
<Style name="coastline" filter-mode="first">
  <Rule>
    <Filter>([ScaleRank] = 6)</Filter>
    <LineSymbolizer stroke-width="0.5" stroke="#000000" />
    <PolygonSymbolizer fill="#ffffff" fill-opacity="0.3" />
  </Rule>
  <Rule>
    <LineSymbolizer stroke-width="0.5" stroke="#000000" />
    <PolygonSymbolizer fill="#ffffff" />
  </Rule>
</Style>
```

Note the additional Rule with a Filter on ScaleRank in the coastline Style.

I know nesting the same zoom does not make sense in a finished stylesheet, but it may appear while testing different zoom configurations...
