### ISSUE TITLE
Empty file="" point_symbolizer attribute being passed to Mapnik

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#159]
Hoping for help from @tmcw and @ajashton on understanding if this is a bug.

This is a followup on https://github.com/mapbox/tilemill/issues/1499.

The issue is that xml like:

``` xml
<PointSymbolizer transform="scale(0.2);" allow-overlap="true" ignore-placement="true" file="" />
```

(Full XML is at https://gist.github.com/2839439)

is being output for css like:

``` css
  point-allow-overlap: true;
  point-ignore-placement: true;
  [zoom < 13] {point-transform: "scale(0.1);"}
  [zoom > 12] {point-transform: "scale(0.2);"}
 ...
```

Full carto is at https://gist.github.com/2839387.

My sense is that `file=""` is wrong - carto should not be setting this unless the user specifically types `point-url()`. Right?
