### ISSUE TITLE
error or warning on #foo[a=b] [a=d]?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#161]
Using `AND` operator syntax like this (where there is no `,` between the selectors):

``` css
#countries[FeatureCla!=""][FeatureCla=""] {
  ::outline {
    line-color: #85c5d3;
    line-width: 2;
    line-join: round;
  }
  polygon-fill: #fff;
}
```

I think used to throw (somewhere) in carto: https://github.com/mapbox/tilemill/issues/1127

But now it creates a Mapnik XML like:

``` xml
<Style name="countries" filter-mode="first" >
  <Rule>
    <Filter>([FeatureCla] = '')</Filter>
    <PolygonSymbolizer fill="#ffffff" />
  </Rule>
</Style>
<Style name="countries-outline" filter-mode="first" >
  <Rule>
    <Filter>([FeatureCla] = '')</Filter>
    <LineSymbolizer stroke="#85c5d3" stroke-width="2" stroke-linejoin="round" />
  </Rule>
</Style>
```

Is this intended behavior?
