### ISSUE TITLE
Support default creation of symbolizers using 'auto' syntax

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#18]
Say I want to create a point without supplying a png/svg file. I know that Mapnik supports creating a PointSymbolizer without any arguments and will internally just create a simple black square. We should have a simple way to request this in carto that can be used for other symbolizers that have a no-arg default contructor, including line, polygon, and markers symbolizer (and perhaps more in the future). Maybe something like:

``` css
    #city {
        point: auto;
    }
```

or

``` css
    #city {
        point-visibility: auto;
    }
```
