### ISSUE TITLE
another parsing error is incorrect

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#188]
This parses and renders just fine:

``` css
#mapbbox120 {
  ::poly {
    ['mapnik::geometry_type'=polygon] {
      polygon-fill:blue;
    }
  }
  ::line {
    ['mapnik::geometry_type'=linestring] {
     line-width:.5;
    }
  }
  ::point {
    ['mapnik::geometry_type'=point] {
     marker-width:5;
    }
  }
}
```

But this does not:

``` css
#mapbbox120 {
  text-name:[osm_id];
  text-face-name:"DejaVu Sans Book;
  ::poly {
    ['mapnik::geometry_type'=polygon] {
      polygon-fill:blue;
    }
  }
  ::line {
    ['mapnik::geometry_type'=linestring] {
     line-width:.5;
    }
  }
  ::point {
    ['mapnik::geometry_type'=point] {
     marker-width:5;
    }
  }
}
```
