### ISSUE TITLE
extra closing bracket only triggers parse error if trailing space or newline is present

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#204]
CSS like this is invalid but does not throw:

``` css
#countries {
  polygon-fill: green;
}}
```

Whereas this does properly throw:

``` css
#countries {
  polygon-fill: green;
}}

```

The difference is subtle. To replicate in TileMill simply make sure that no extra space or lines are present after the `}}`. Curiously, after no error is thrown the map still displays correctly.
