### ISSUE TITLE
Unmatched { does not properly throw

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#218]
This does not throw:

``` css
#country-label {
  [one = 2]
    marker-width:1;
  }
}
```

It should since there is a missing `{` after the `[one = 2]`.

If you add a newline at the end of the block then it does throw.
