### ISSUE TITLE
Carto may generate style reference on layer for empty/non-existant style

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#244]
After #219 we now properly drop empty styles. But still with a style like:

``` css
#world {
  ::outline {
      line-color: #000000;
    }
  ::fill {
      line-color: #ffffff;
  }
}
```

While only two styles are generated (correctly) the layer will end up with:

``` xml
    <StyleName>world-outline</StyleName>
    <StyleName>world-fill</StyleName>
    <StyleName>world</StyleName>
```

The style `world` references nothing and should not be placed. This may require a better fix than I made in #219
