### ISSUE TITLE
image-filters are duplicated per rule

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#270]
Currently a style like:

``` css
#layer {
    image-filters:agg-stack-blur(3,3);
    [zoom=2] { line-width: 3; }
    [zoom=3] { line-width: 5; }
}
```

Will have the `agg-stack-blur(3,3)` repeated 3 times, once per rule. This is a potentially severe bug because image-filters are fairly expensive for rendering and styles may have many rules. It looks like this has been this way in Carto for some time.

Output XML is:

``` xml
<Style name="style" filter-mode="first" image-filters="agg-stack-blur(3,3),agg-stack-blur(3,3),agg-stack-blur(3,3)" opacity="0.5">
  <Rule>
    <MaxScaleDenominator>100000000</MaxScaleDenominator>
    <MinScaleDenominator>50000000</MinScaleDenominator>
    <LineSymbolizer stroke-width="5" />
  </Rule>
  <Rule>
    <MaxScaleDenominator>200000000</MaxScaleDenominator>
    <MinScaleDenominator>100000000</MinScaleDenominator>
    <LineSymbolizer stroke-width="3" />
  </Rule>
</Style>
```
