### ISSUE TITLE
Zoom levels 19+ are off

### ISSUE THREAD

**Issue by ajashton** [mapbox/carto#48]
With the following test code,  the rule for zoom=18 gets applied to zoom level 19 as well (in TileMill). The rules for zoom=19 and above are then all off by one in the preview. Zoom level 22 is blank. I suspect this is due to incorrect zoom level definitions in Carto.

``` css
#world {
  polygon-fill: grey;
  line-color: black;
  [zoom=22] { polygon-fill: white; }
  [zoom=21] { polygon-fill: magenta; }
  [zoom=20] { polygon-fill: blue; }
  [zoom=19] { polygon-fill: green; }
  [zoom=18] { polygon-fill: yellow; }
  [zoom=17] { polygon-fill: red; }
}
```
