### ISSUE TITLE
zoom selector is ignored

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#81]
Seems to me that both of these styles should have the same effect. But the one above does not show any data _until_ zoom 4. Found this when going through http://support.mapbox.com/kb/tilemill/styling-point-data-using-tilemill which used the first style below until I changed it to workaround this bug.

``` css
#data {
    [zoom>9] { marker-height: 4; }
    [zoom>6][zoom<10] { marker-height: 3; }
    [zoom>3][zoom<7] { marker-height: 2; }
    [zoom<4] { marker-height: 1; }
}
```

and

``` css
#data {
    [zoom>9] { marker-height: 4; }
    [zoom>6][zoom<10] { marker-height: 3; }
    [zoom>3][zoom<7] { marker-height: 2; }
    [zoom>0][zoom<4] { marker-height: 1; }
}
```
